Add OPKG remove test
CreatorDev/boardfarm pull request #32
Opened 2017-03-03 10:29 UTC by nikhil-zinjurde-imgtec

This closes #26

2017-03-03 11:56 UTC, nikhil-zinjurde-imgtec commented
This was tested by
* expecting an incorrect console output
* removing a kmod package (kmod-usb-net-qmi-wwan) and re-running bft to ensure DUT upgrade is still done successfully for the next run of tests

2017-03-03 11:58 UTC, mtusnio requested changes
One additional check I'm thinking of is to do an opkg list-installed at least after the test to double check if all packages are gone from the list as advertised.

2017-03-03 13:43 UTC, mtusnio submitted a review, later dismissed

2017-03-03 13:43 UTC, mtusnio commented on tests/opkg.py
> +        packages = [ "nano", "mrd6", "libssh", "glog", "miax", "luci-mod-rpc" , "kmod-usb-net-qmi-wwan" ]
One more thing actually, if the idea is to remove what's been installed by opkg install than this array could be shared between the two tests, with the kmod being added only in this test.

2017-03-03 14:16 UTC, nikhil-zinjurde-imgtec commented on tests/opkg.py
> +        packages = [ "nano", "mrd6", "libssh", "glog", "miax", "luci-mod-rpc" , "kmod-usb-net-qmi-wwan" ]
Though the idea may have started on those lines, I would rather keep the lists separate so that we can change the packages as needed in future.

2017-03-03 15:14 UTC, mtusnio commented on tests/opkg.py
> +        packages = [ "nano", "mrd6", "libssh", "glog", "miax", "luci-mod-rpc" , "kmod-usb-net-qmi-wwan" ]
Sounds good then, I guess in the future we can think about adding some kind of a dictionary with packages if we need to remove/install them depending on the feeds in different tests.

2017-03-06 09:53 UTC, mtusnio approved these changes

2017-03-06 10:27 UTC, merged